---
- hosts: webservers
  sudo: yes 
  remote_user: ec2-user 
  
  tasks:
  - name: install httpd
    yum: name=httpd state=latest 
  - name: ensure httpd is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
    notify:
    - restart httpd
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
