---
- hosts: webservers
  sudo: yes 
  remote_user: ec2-user 
  
  tasks:

  
  - name: 1.install httpd
    yum: name=httpd state=latest
  
  - name: 2.ensure httpd is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
  
