---
- hosts: webservers
  sudo: yes 
  remote_user: ec2-user 
  
  tasks:

  
  - name: Download MySQL Community Repo
    get_url:
      url: http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
      dest: /tmp

  - name: Install MySQL Community Repo
    command: /usr/bin/rpm -ivh /tmp/mysql-community-release-el7-7.noarch.rpm

  - name: 1. Install MariaDB server package
    yum: name={{ item }} state=present
    with_items:
       - mysql-server
       - MySQL-python
  - name: 2. Start Mysql Service
    service: name=mysqld state=started enabled=true

  #- name: Install python Mysql package #required for mysql_db tasks
  #  yum: name=python-mysqldb state=present

  - name: 3. Create a new database
    mysql_db: name=demo state=present collation=utf8_general_ci

  - name: 4. Create a database user
    mysql_user: name=demo password=demo priv=*.*:ALL host=localhost state=present

  - name: 5a. Copy sample data
    copy: src=dump.sql dest=/tmp/dump.sql

  - name: 5b. Insert sample data
    shell: cat /tmp/dump.sql | mysql -u demo -pdemo demo

  - name: 6. Install MySQL extension for PHP
    yum: name={{ item }} state=present
    with_items:
       - php
       - php-mysqlnd


  - name: 7.install httpd
    yum: name=httpd state=latest
  
  - name: 8.ensure httpd is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
  - name: 9. install Hello World PHP script with database
    copy: src=db.php dest=/var/www/html/db.php mode=0664
