---
- hosts: localhost
  connection: "local"
  gather_facts: false
  vars:
    region: "us-east-1"
    v_id: "v_id"
    zone: "zone"
    desc: "desc"

  tasks:
  
   - name: "Snapshot of Volume"
     ec2_snapshot:
       volume_id: "{{ v_id }}"
       description: "{{ desc }}" 
       region: "{{ region }}"
       #zone: "{{ zone }}"

ansible-playbook snapshot_volume.yml  --extra-vars "v_id=vol-0507f4cf9bbec6fe4 region=us-east-1"
